sonar.projectKey=hient4680-hue_hospital-api-testing
sonar.organization=hient4680-hue

sonar.host.url=https://sonarcloud.io
sonar.token=061b2357c2a571d6ce2a0ac0b0c6183314e725cb

sonar.sources=hospital-API-main/src

sonar.exclusions=\
**/node_modules/**,\
**/coverage/**,\
**/.nyc_output/**,\
**/*.log

sonar.javascript.file.suffixes=.js,.mjs
sonar.javascript.environments=node