name: Kiem thu tu dong Hospital API

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cai dependencies
        run: npm install

      - name: Cai Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          npm install -g nyc

      - name: Khoi dong server
        run: |
          nohup npm start > server.log 2>&1 &
          sleep 60

          echo "===== SERVER LOG ====="
          cat server.log

          echo "===== CHECK SERVER ====="
          curl http://localhost:3000 || exit 1
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Chay Newman
        run: |
          newman run HospitalAPI_Collection.json \
          -e HospitalAPI_Environment.json \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export BaoCao_Newman.html

      - name: Luu bao cao
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: newman-report
          path: BaoCao_Newman.html